/** @type {import('tailwindcss').Config} */
import colours from "./tailwind.colours.js";

export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
        "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}",
    ],
    blocklist: [
        'underline',
    ],
    theme: {
        extend: {
          boxShadow: {
            'bottom-only': '0 4px 6px -6px rgb(0 0 0 / .4)'
          },
          backgroundImage: {
            'archive-stripe': `linear-gradient(to bottom left,${colours.archive_stripe_strong} 25%, ${colours.archive_stripe_lite} 25%,${colours.archive_stripe_lite} 50%,${colours.archive_stripe_strong} 50%,${colours.archive_stripe_strong} 75%,${colours.archive_stripe_lite} 75%, ${colours.archive_stripe_lite})`,
          },
          backgroundSize: {
            'archive-stripe-size': '1rem 1rem',
          },
        },
        borderRadius: {
            none: "0px",
            sm: "0.125rem", // 2px
            DEFAULT: "0.25rem", // 4px
            md: "0.375rem", // 6px
            lg: "0.5rem", // 8px
            xl: "0.75rem", // 12px
            "2xl": "1rem", // 16px
            "hero": "20px",
            "3xl": "1.5rem", // 24px
            full: "9999px",
        },
        fontSize: {
            xxs: "0.6875rem", // 11px
            xs: "0.75rem", // 12px
            sm: "0.875rem", // 14px
            base: "1rem", // 16px
            mid: "1.0625rem", // 17px
            lg: "1.125rem", // 18px
            xl: "1.313rem", // 21px
            "2xl": "1.375rem", // 22px
            "3xl": "1.5rem", // 24px
            "4xl": "1.625rem", // 26px
            iconlarge: "2rem",
        },
        colors: {
            'transparent': 'transparent',
            'white': colours.white,
            'black': colours.black,
            'backgrounds-blurred-bar': '#FFFFFF99',
            'backgrounds-modal-overlay': '#00000099',
            'backgrounds-segment-track': colours.neutral_200,
            'backgrounds-selected-segment': colours.white,
            'backgrounds-white-sheet': colours.white,
            'backgrounds-cards-backing': colours.neutral_200,
            'backgrounds-cards-error-text': colours.attention_600,
            'backgrounds-cards-error': colours.attention_50,
            'backgrounds-cards-inactive': colours.neutral_50,
            'backgrounds-cards-lift-inactive': colours.neutral_200,
            'backgrounds-cards-lift-rest': colours.neutral_100,
            'backgrounds-cards-rest': colours.white,
            'backgrounds-headers-primary': colours.primary_100,
            'backgrounds-headers-secondary': colours.primary_50,
            'backgrounds-inputs-disabled': colours.neutral_200,
            'backgrounds-inputs-rest': colours.white,
            'backgrounds-meccano-sections-level-1': colours.primary_50,
            'backgrounds-meccano-sections-level-2': colours.primary_100,
            'backgrounds-meccano-sections-level-3': colours.primary_200,
            'backgrounds-meccano-sections-level-4': colours.primary_300,
            'backgrounds-search-active': colours.neutral_200,
            'backgrounds-search-rest': colours.neutral_100,
            'backgrounds-sidebar-active': colours.primary_200,
            'backgrounds-sidebar-hover': colours.primary_50,
            'backgrounds-table-cells-active': colours.accent2_100,
            'backgrounds-table-cells-disabled': colours.neutral_100,
            'backgrounds-table-cells-focused': colours.accent2_50,
            'backgrounds-table-cells-hover': colours.accent2_50,
            'backgrounds-table-cells-active-lift': colours.accent2_200,
            'backgrounds-table-cells-rest': colours.white,
            'backgrounds-translucent-active': '#00000080',
            'backgrounds-translucent-focus': '#00000033',
            'backgrounds-translucent-focus-ring': '#0000001A',
            'backgrounds-translucent-hover': '#0000001A',
            'backgrounds-upgrade-panel-circles': colours.white,
            'backgrounds-upgrade-panel-primary-button': colours.accent2_600,
            'backgrounds-upgrade-panel-secondary-button': colours.white,
            'badges-blue-label': colours.white,
            'badges-green-label': colours.white,
            'badges-orange-label': colours.white,
            'badges-primary-background': colours.neutral_700,
            'badges-primary-label': colours.white,
            'badges-red-label': colours.white,
            'badges-secondary-background': colours.neutral_300,
            'badges-secondary-label': colours.neutral_500,
            'badges-tertiary-background': colours.neutral_50,
            'badges-tertiary-label': colours.neutral_500,
            'badges-yellow-label': colours.neutral_600,
            'borders-avatar': colours.accent3_600,
            'borders-dashed-row': colours.accent2_200,
            'borders-divider': colours.neutral_200,
            'borders-image-container': colours.accent2_300,
            'borders-meccano-section': colours.accent2_600,
            'borders-thumbnail': '#00000033',
            'borders-toolbar': colours.neutral_200,
            'borders-upgrade-panel': colours.accent2_300,
            'borders-cards-error': colours.attention_100,
            'borders-cards-inactive': '#FFFFFF00',
            'borders-cards-rest': '#FFFFFF00',
            'borders-input-focused': colours.primary_500,
            'borders-input-hover': colours.neutral_500,
            'borders-input-rest': colours.neutral_300,
            'illustrations-green': colours.positive_100,
            'illustrations-outline': colours.primary_400,
            'illustrations-primary': colours.white,
            'illustrations-secondary': colours.neutral_100,
            'illustrations-shadow': colours.info_100,
            'illustrations-yellow-primary': colours.warning_100,
            'illustrations-yellow-secondary': colours.warning_50,
            'levels-alt-accent-1-base': colours.accent1_300,
            'levels-alt-accent-1-deep': colours.accent1_50,
            'levels-alt-accent-1-mid': colours.accent1_500,
            'levels-alt-accent-1-top': colours.accent1_600,
            'levels-alt-accent-1-under': colours.accent1_100,
            'levels-alt-accent-2-base': colours.accent2_300,
            'levels-alt-accent-2-deep': colours.accent2_50,
            'levels-alt-accent-2-mid': colours.accent2_500,
            'levels-alt-accent-2-top': colours.accent2_600,
            'levels-alt-accent-2-under': colours.accent2_100,
            'levels-alt-accent-3-base': colours.accent3_300,
            'levels-alt-accent-3-deep': colours.accent3_50,
            'levels-alt-accent-3-mid': colours.accent3_500,
            'levels-alt-accent-3-top': colours.accent3_800,
            'levels-alt-accent-3-under': colours.accent3_100,
            'levels-alt-attention-base': colours.attention_300,
            'levels-alt-attention-deep': colours.attention_50,
            'levels-alt-attention-mid': colours.attention_500,
            'levels-alt-attention-top': colours.attention_600,
            'levels-alt-attention-under': colours.attention_100,
            'levels-alt-info-base': colours.info_300,
            'levels-alt-info-deep': colours.info_50,
            'levels-alt-info-mid': colours.info_500,
            'levels-alt-info-top': colours.info_600,
            'levels-alt-info-under': colours.info_100,
            'levels-alt-neutrals-base': colours.neutral_300,
            'levels-alt-neutrals-deep': colours.neutral_50,
            'levels-alt-neutrals-mid': colours.neutral_400,
            'levels-alt-neutrals-top': colours.neutral_600,
            'levels-alt-neutrals-under': colours.neutral_100,
            'levels-alt-positive-base': colours.positive_300,
            'levels-alt-positive-deep': colours.positive_50,
            'levels-alt-positive-mid': colours.positive_500,
            'levels-alt-positive-top': colours.positive_700,
            'levels-alt-positive-under': colours.positive_100,
            'levels-alt-primary-base': colours.primary_300,
            'levels-alt-primary-deep': colours.primary_50,
            'levels-alt-primary-mid': colours.primary_500,
            'levels-alt-primary-top': colours.primary_600,
            'levels-alt-primary-under': colours.primary_100,
            'levels-alt-warning-base': colours.warning_300,
            'levels-alt-warning-deep': colours.warning_50,
            'levels-alt-warning-mid': colours.warning_500,
            'levels-alt-warning-top': colours.warning_700,
            'levels-alt-warning-under': colours.warning_100,
            'levels-main-accent-1-base': colours.accent1_300,
            'levels-main-accent-1-deep': colours.accent1_50,
            'levels-main-accent-1-mid': colours.accent1_500,
            'levels-main-accent-1-top': colours.accent1_600,
            'levels-main-accent-1-under': colours.accent1_100,
            'levels-main-accent-2-base': colours.accent2_300,
            'levels-main-accent-2-deep': colours.accent2_50,
            'levels-main-accent-2-mid': colours.accent2_500,
            'levels-main-accent-2-top': colours.accent2_600,
            'levels-main-accent-2-under': colours.accent2_100,
            'levels-main-accent-3-base': colours.accent3_300,
            'levels-main-accent-3-deep': colours.accent3_50,
            'levels-main-accent-3-mid': colours.accent3_500,
            'levels-main-accent-3-top': colours.accent3_800,
            'levels-main-accent-3-under': colours.accent3_100,
            'levels-main-attention-base': colours.attention_300,
            'levels-main-attention-deep': colours.attention_50,
            'levels-main-attention-mid': colours.attention_500,
            'levels-main-attention-top': colours.attention_600,
            'levels-main-attention-under': colours.attention_100,
            'levels-main-info-base': colours.info_300,
            'levels-main-info-deep': colours.info_50,
            'levels-main-info-mid': colours.info_500,
            'levels-main-info-top': colours.info_600,
            'levels-main-info-under': colours.info_100,
            'levels-main-neutrals-base': colours.neutral_300,
            'levels-main-neutrals-deep': colours.neutral_50,
            'levels-main-neutrals-mid': colours.neutral_400,
            'levels-main-neutrals-top': colours.neutral_600,
            'levels-main-neutrals-under': colours.neutral_100,
            'levels-main-positive-base': colours.positive_300,
            'levels-main-positive-deep': colours.positive_50,
            'levels-main-positive-mid': colours.positive_500,
            'levels-main-positive-top': colours.positive_700,
            'levels-main-positive-under': colours.positive_100,
            'levels-main-primary-base': colours.primary_300,
            'levels-main-primary-deep': colours.primary_50,
            'levels-main-primary-mid': colours.primary_500,
            'levels-main-primary-top': colours.primary_600,
            'levels-main-primary-under': colours.primary_100,
            'levels-main-warning-base': colours.warning_300,
            'levels-main-warning-deep': colours.warning_50,
            'levels-main-warning-mid': colours.warning_500,
            'levels-main-warning-top': colours.warning_700,
            'levels-main-warning-under': colours.warning_100,
            'tints-ui-chrome': colours.black,
            'tints-button-label-inverse': colours.black,
            'tints-button-label': colours.white,
            'tints-unselected-tab': colours.primary_300,
            'tints-callout-primary': colours.primary_700,
            'tints-callout-secondary': colours.primary_500,
            'tints-inactive-active': colours.neutral_400,
            'tints-inactive-focused': colours.neutral_500,
            'tints-inactive-hover': colours.neutral_100,
            'tints-inactive-rest': colours.neutral_200,
            'tints-text-primary': colours.neutral_600,
            'tints-text-quaternary': colours.neutral_100,
            'tints-text-secondary': colours.neutral_400,
            'tints-text-tertiary': colours.neutral_300,

            // Button colours
            default: {
                primary: {
                    rest: colours.accent3_800,
                    font: colours.white,
                    hover: colours.accent3_500,
                    active: colours.accent3_300,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.accent3_800,
                    hover: colours.accent3_50,
                    active: colours.accent3_100,
                    border: colours.accent3_800,
                },
            },
            danger: {
                primary: {
                    rest: colours.attention_500,
                    font: colours.white,
                    hover: colours.attention_300,
                    active: colours.attention_300,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.attention_500,
                    hover: colours.attention_50,
                    active: colours.attention_100,
                    border: colours.attention_500,
                },
            },
            success: {
                primary: {
                    rest: colours.positive_500,
                    font: colours.white,
                    hover: colours.positive_300,
                    active: colours.positive_300,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.positive_500,
                    hover: colours.positive_50,
                    active: colours.positive_100,
                    border: colours.positive_500,
                },
            },
            upgrade: {
                primary: {
                    rest: colours.accent2_600,
                    font: colours.white,
                    hover: colours.accent2_500,
                    active: colours.accent2_500,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.accent2_600,
                    hover: colours.accent2_50,
                    active: colours.accent2_100,
                    border: colours.accent2_600,
                },
            },
            info: {
                primary: {
                    rest: colours.info_600,
                    font: colours.white,
                    hover: colours.info_500,
                    active: colours.info_500,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.info_600,
                    hover: colours.info_50,
                    active: colours.info_100,
                    border: colours.info_600,
                },
            },
            warning: {
                primary: {
                    rest: colours.warning_700,
                    font: colours.white,
                    hover: colours.warning_500,
                    active: colours.warning_500,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.warning_700,
                    hover: colours.warning_50,
                    active: colours.warning_100,
                    border: colours.warning_700,
                },
            },
            automation: {
                primary: {
                    rest: colours.accent1_500,
                    font: colours.white,
                    hover: colours.accent1_300,
                    active: colours.accent1_300,
                    border: "transparent",
                },
                secondary: {
                    rest: "transparent",
                    font: colours.accent1_500,
                    hover: colours.accent1_50,
                    active: colours.accent1_100,
                    border: colours.accent1_500,
                },
            },
        },
    },
    plugins: [],
    corePlugins: {
        /*
            Due to Button background missing, we need to disable preflight to avoid
            See link: https://stackoverflow.com/questions/73308849/primevue-tailwind-conflict-button-background-missing
        */
        preflight: false,
    },
};
